# 2022 년 5월 식품 ID, 식품 이름, 총매출 (가격 * 생산량)
SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fp.PRICE * fo.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT AS fp
INNER JOIN FOOD_ORDER AS fo
ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE DATE_FORMAT(fo.PRODUCE_DATE, '%y%m') = 2205
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;

